/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:be1a58ac-1d9e-42c0-b598-7cd1109da2d8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lII7VB5ee",
    "aws_user_pools_web_client_id": "2u9jd6sfgqp11e2p41ecqr8rk3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bhfzkmsse5fezkvvbeoa6625hu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-s2f2pv5bavb7jmxivexz7frv2a"
};


export default awsmobile;
